*** Starting uWSGI 2.0.19.1 (64bit) on [Fri May 21 15:30:41 2021] ***
compiled with version: 9.3.0 on 26 February 2021 14:44:01
os: Linux-5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
nodename: yanmu
machine: x86_64
clock source: unix
detected number of CPU cores: 6
current working directory: /home/yanmu/桌面/ciyun/ciyunapi
writing pidfile to uwsgi.pid
detected binary path: /home/yanmu/.virtualenvs/django/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/yanmu/桌面/ciyun/ciyunapi
your processes number limit is 33972
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:35701 (port auto-assigned) fd 3
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15)  [GCC 9.3.0]
!!! Python Home is not a directory: /root/.virtualenvs/django !!!
Set PythonHome to /root/.virtualenvs/django
Python path configuration:
  PYTHONHOME = '/root/.virtualenvs/django'
  PYTHONPATH = (not set)
  program name = '/root/.virtualenvs/django/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/root/.virtualenvs/django/bin/python'
  sys.base_prefix = '/root/.virtualenvs/django'
  sys.base_exec_prefix = '/root/.virtualenvs/django'
  sys.executable = '/root/.virtualenvs/django/bin/python'
  sys.prefix = '/root/.virtualenvs/django'
  sys.exec_prefix = '/root/.virtualenvs/django'
  sys.path = [
    '/root/.virtualenvs/django/lib/python38.zip',
    '/root/.virtualenvs/django/lib/python3.8',
    '/root/.virtualenvs/django/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ffa879cbb80 (most recent call first):
<no Python frame>
